# DO NOT EDIT THIS FILE!
#
# Python module IntLibraryApp generated by omniidl

import omniORB
omniORB.updateModule("IntLibraryApp")

# ** 1. Stub files contributing to this module
import IntLibrary_idl

# ** 2. Sub-modules

# ** 3. End
