# Python stubs generated by omniidl from IntLibrary.idl

import omniORB, _omnipy
from omniORB import CORBA, PortableServer
_0_CORBA = CORBA

_omnipy.checkVersion(3,0, __file__)


#
# Start of module "IntLibraryApp"
#
__name__ = "IntLibraryApp"
_0_IntLibraryApp = omniORB.openModule("IntLibraryApp", r"IntLibrary.idl")
_0_IntLibraryApp__POA = omniORB.openModule("IntLibraryApp__POA", r"IntLibrary.idl")


# interface IntLibrary
_0_IntLibraryApp._d_IntLibrary = (omniORB.tcInternal.tv_objref, "IDL:IntLibraryApp/IntLibrary:1.0", "IntLibrary")
omniORB.typeMapping["IDL:IntLibraryApp/IntLibrary:1.0"] = _0_IntLibraryApp._d_IntLibrary
_0_IntLibraryApp.IntLibrary = omniORB.newEmptyClass()
class IntLibrary :
    _NP_RepositoryId = _0_IntLibraryApp._d_IntLibrary[1]

    def __init__(self, *args, **kw):
        raise RuntimeError("Cannot construct objects of this type.")

    _nil = CORBA.Object._nil


_0_IntLibraryApp.IntLibrary = IntLibrary
_0_IntLibraryApp._tc_IntLibrary = omniORB.tcInternal.createTypeCode(_0_IntLibraryApp._d_IntLibrary)
omniORB.registerType(IntLibrary._NP_RepositoryId, _0_IntLibraryApp._d_IntLibrary, _0_IntLibraryApp._tc_IntLibrary)

# IntLibrary operations and attributes
IntLibrary._d_procesarPeticion = ((omniORB.tcInternal.tv_short, omniORB.tcInternal.tv_short, omniORB.tcInternal.tv_short), (omniORB.tcInternal.tv_ushort, ), None)
IntLibrary._d_shutdown = ((), None, None)

# IntLibrary object reference
class _objref_IntLibrary (CORBA.Object):
    _NP_RepositoryId = IntLibrary._NP_RepositoryId

    def __init__(self):
        CORBA.Object.__init__(self)

    def procesarPeticion(self, *args):
        return _omnipy.invoke(self, "procesarPeticion", _0_IntLibraryApp.IntLibrary._d_procesarPeticion, args)

    def shutdown(self, *args):
        return _omnipy.invoke(self, "shutdown", _0_IntLibraryApp.IntLibrary._d_shutdown, args)

    __methods__ = ["procesarPeticion", "shutdown"] + CORBA.Object.__methods__

omniORB.registerObjref(IntLibrary._NP_RepositoryId, _objref_IntLibrary)
_0_IntLibraryApp._objref_IntLibrary = _objref_IntLibrary
del IntLibrary, _objref_IntLibrary

# IntLibrary skeleton
__name__ = "IntLibraryApp__POA"
class IntLibrary (PortableServer.Servant):
    _NP_RepositoryId = _0_IntLibraryApp.IntLibrary._NP_RepositoryId


    _omni_op_d = {"procesarPeticion": _0_IntLibraryApp.IntLibrary._d_procesarPeticion, "shutdown": _0_IntLibraryApp.IntLibrary._d_shutdown}

IntLibrary._omni_skeleton = IntLibrary
_0_IntLibraryApp__POA.IntLibrary = IntLibrary
omniORB.registerSkeleton(IntLibrary._NP_RepositoryId, IntLibrary)
del IntLibrary
__name__ = "IntLibraryApp"

#
# End of module "IntLibraryApp"
#
__name__ = "IntLibrary_idl"

_exported_modules = ( "IntLibraryApp", )

# The end.
