/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _INT_LIBRARY_H_RPCGEN
#define _INT_LIBRARY_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct argumento {
	int type;
	int op1;
	int op2;
};
typedef struct argumento argumento;

struct resultado {
	int res;
};
typedef struct resultado resultado;

#define INT_LIBRARY_PROG 0x00000007
#define INT_LIBRARY_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define PROCESAPETICION 1
extern  resultado * procesapeticion_1(argumento *, CLIENT *);
extern  resultado * procesapeticion_1_svc(argumento *, struct svc_req *);
extern int int_library_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define PROCESAPETICION 1
extern  resultado * procesapeticion_1();
extern  resultado * procesapeticion_1_svc();
extern int int_library_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_argumento (XDR *, argumento*);
extern  bool_t xdr_resultado (XDR *, resultado*);

#else /* K&R C */
extern bool_t xdr_argumento ();
extern bool_t xdr_resultado ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_INT_LIBRARY_H_RPCGEN */
