/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "int_library.h"

bool_t
xdr_argumento (XDR *xdrs, argumento *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->type))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->op1))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->op2))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_resultado (XDR *xdrs, resultado *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->res))
		 return FALSE;
	return TRUE;
}
