package IntLibraryApp;


/**
* IntLibraryApp/IntLibraryPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from IntLibrary.idl
* Wednesday, February 10, 2016 10:28:47 AM PST
*/

public abstract class IntLibraryPOA extends org.omg.PortableServer.Servant
 implements IntLibraryApp.IntLibraryOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("procesarPeticion", new java.lang.Integer (0));
    _methods.put ("shutdown", new java.lang.Integer (1));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // IntLibraryApp/IntLibrary/procesarPeticion
       {
         short type = in.read_short ();
         short op1 = in.read_short ();
         short op2 = in.read_short ();
         short $result = (short)0;
         $result = this.procesarPeticion (type, op1, op2);
         out = $rh.createReply();
         out.write_ushort ($result);
         break;
       }

       case 1:  // IntLibraryApp/IntLibrary/shutdown
       {
         this.shutdown ();
         out = $rh.createReply();
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:IntLibraryApp/IntLibrary:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public IntLibrary _this() 
  {
    return IntLibraryHelper.narrow(
    super._this_object());
  }

  public IntLibrary _this(org.omg.CORBA.ORB orb) 
  {
    return IntLibraryHelper.narrow(
    super._this_object(orb));
  }


} // class IntLibraryPOA
