package IntLibraryApp;


/**
* IntLibraryApp/IntLibraryOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from IntLibrary.idl
* Wednesday, February 10, 2016 10:28:47 AM PST
*/

public interface IntLibraryOperations 
{
  short procesarPeticion (short type, short op1, short op2);
  void shutdown ();
} // interface IntLibraryOperations
