package IntLibraryApp;


/**
* IntLibraryApp/IntLibrary.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from IntLibrary.idl
* Wednesday, February 10, 2016 10:28:47 AM PST
*/

public interface IntLibrary extends IntLibraryOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface IntLibrary
