package IntLibraryApp;

/**
* IntLibraryApp/IntLibraryHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from IntLibrary.idl
* Wednesday, February 10, 2016 10:28:47 AM PST
*/

public final class IntLibraryHolder implements org.omg.CORBA.portable.Streamable
{
  public IntLibraryApp.IntLibrary value = null;

  public IntLibraryHolder ()
  {
  }

  public IntLibraryHolder (IntLibraryApp.IntLibrary initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = IntLibraryApp.IntLibraryHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    IntLibraryApp.IntLibraryHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return IntLibraryApp.IntLibraryHelper.type ();
  }

}
